import Foundation
import Darwin

func clearScreen() {
    Process.launchedProcess(launchPath: "/usr/bin/clear", arguments: []).waitUntilExit()
}

clearScreen()
print("Tee it up!")

sleep(2)
clearScreen()

print()
print()
print()
print()
print()
print()
print()
print("   ------")
print("   \\    /")
print("    \\  /")
print("     \\/")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print()
sleep(2)
clearScreen()

print("    ooooo   ")
print("  ooo   ooo")
print(" oo       oo")
print("o           o")
print(" oo       oo")
print("  ooo   ooo")
print("    ooooo")
print("   ------")
print("   \\    /")
print("    \\  /")
print("     \\/")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print("     ||")
print()
sleep(2)
clearScreen()

print("Now smack that ball son!")
sleep(2)
clearScreen()

print()
print()
print()
print()
print()
print()
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()


print("          /")
print("    ____")
print("    \\ - \\")
print("     ----")
print()
print()
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("           /")
print("          /")
print("    ____")
print("    \\ - \\")
print("     ----")
print()
print()
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("            /")
print("           /")
print("          /")
print("    _____")
print("    \\ -- \\")
print("     -----")
print()
print()
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("             /")
print("            /")
print("           /")
print("          /")
print("    _____")
print("    \\ -- \\")
print("     -----")
print()
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("               /")
print("              /")
print("             /")
print("            /")
print("           /")
print("  ________")
print("  \\ ----  \\")
print("   \\ ----  \\")
print("     --------")
print()
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                /")
print("               /")
print("              /")
print("             /")
print("            /")
print("           /")
print("  ________")
print("  \\ ----  \\")
print("   \\ ----  \\")
print("     --------")
print()
print("      ooo   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                 /")
print("                /")
print("               /")
print("              /")
print("             /")
print("            /")
print("  _________")
print("  \\ -----  \\")
print("   \\ -----  \\")
print("    --ooo--   ")
print("    oo   oo")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                 /")
print("                /")
print("               /")
print("              /")
print("             /")
print("            /")
print("  _________")
print("  \\ -----  \\")
print("   \\ ooo--  \\")
print("    oo   oo-")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                 /")
print("                /")
print("               /")
print("              /")
print("             /")
print("            /")
print("  _________")
print("  \\ -ooo-  \\")
print("    oo   oo  \\")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                 /")
print("                /")
print("               /")
print("              /")
print("             /")
print("            /")
print("  ____ooo__")
print("  \\oo   oo \\")
print("   o       o")
print("    oo   oo")
print("      ooo")
print("      ---")
print("      \\ /")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                 /")
print("                /")
print("               /")
print("              /")
print("             /")
print("          oooooo")
print("      ooooo    ooooo")
print("   oooo            oooo")
print(" ooo                  ooo")
print("oo                      oo")
print("o                        o")
print("oo                      oo")
print(" ooo                  ooo")
print("   oooo            oooo")
print("      ooooo    ooooo")
print("          oooooo")
print("       V")
print("       |")
print("       |")
print("       |")
print("       |")
print()
sleep(1)
clearScreen()

print("                             oooooo")
print("                        oooooo     ooooo")
print("                   ooooo                ooooo")
print("               ooooo                       ooooo")
print("           oooo                                 oooo")
print("         oooo                                      oooo")
print("      ooo                                              ooo")
print("    ooo                                                  ooo")
print("  oo                                                        oo")
print(" oo                                                          oo")
print(" oo                                                          oo")
print("o                                                              o")
print("o                                                              o")
print("o                                                              o")
print(" oo                                                          oo")
print(" oo                                                          oo")
print("  oo                                                        oo")
print("    ooo                                                  ooo")
print("      ooo                                              ooo")
print("         oooo                                      oooo")
print("            oooo                                oooo")
print("                ooooo                      ooooo")
print("                    ooooo              ooooo")
print("                        oooooo     oooooo")
print("                             oooooo")
sleep(1)
clearScreen()

print("And it is out of here!")
sleep(2)
clearScreen()

print("THE END!!")
sleep(4)
